local t = require('modutram_types')
local Matrix = require('modutram_matrix')
local Position = require('modutram_position')

function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "passenger", },
        },
        description = {
            name = _("Passenger platform"),
            description = _("Platform for waiting passengers."),
            icon = "ui/construction/station/street/platform_passenger_era_a.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "eisfeuer_modutram_platform_double",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            result.station.builder:add_model({
                id = 'station/tram/modutram_platform_double_rep_era_c.mdl',
                transf = transform
            })
            if result.station:is_top_segment_of_a_platform(slotId) then 
                result.station.builder:add_model({
                    id = 'station/tram/modutram_platform_double_noaccess_era_b.mdl',
                    transf = Position:new{x = 0, y = 9, z = 0}:add_to_matrix(transform)
                })
            end
            if result.station:is_bottom_segment_of_a_platform(slotId) then
                result.station.builder:add_model({
                    id = 'station/tram/modutram_platform_double_noaccess_era_b.mdl',
                    transf = Position:new{x = 0, y = -9, z = 0}:add_to_matrix(Matrix.rotate_around_z_axis(180, transform))
                })
            end

            -- Shelters
            result.station.slots:make_asset_slot(slotId, 1, transform):of_type(t.ASSET_SHELTER, 'g_shelter'):move(-0.9, 0, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 2, transform):of_type(t.ASSET_SHELTER, 'g_shelter'):move(0.9, 0, 1.15):rotate(180):add_to_slots()
            if not result.station:is_top_segment_of_a_platform(slotId) then
                result.station.slots:make_asset_slot(slotId, 3, transform):of_type(t.ASSET_SHELTER, 'g_shelter'):move(-0.9, 9, 1.15):add_to_slots()
                result.station.slots:make_asset_slot(slotId, 4, transform):of_type(t.ASSET_SHELTER, 'g_shelter'):move(0.9, 9, 1.15):rotate(180):add_to_slots()
            end

            -- Lamps
            result.station.slots:make_asset_slot(slotId, 1, transform):move(0, -9, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 2, transform):move(0, 0, 1.15):add_to_slots()
            if result.station:is_top_segment_of_a_platform(slotId) then
                result.station.slots:make_asset_slot(slotId, 3, transform):move(0, 9, 1.15):add_to_slots()
            end

            -- Other Decoration Between Lamps
            result.station.slots:make_asset_slot(slotId, 4, transform):move(0, -6, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 5, transform):move(0, -3, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 6, transform):move(0, 3, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 7, transform):move(0, 6, 1.15):add_to_slots()

            -- Stop Signs and Destination Display
            result.station.slots:make_asset_slot(slotId, 8, transform):move(0, -8.2, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 9, transform):move(0, 0, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 10, transform):move(0, 8.2, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 11, transform):move(-0.5, 9, 1.15):rotate(180):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 12, transform):move(-0.5, 0, 1.15):rotate(180):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 13, transform):move(0.5, 9, 1.15):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 14, transform):move(0.5, 0, 1.15):add_to_slots()

            -- Station Signs
            result.station.slots:make_asset_slot(slotId, 1, transform):of_type(t.ASSET_STATION_SIGN, 'eisfeuer_modutram_station_sign')
                :move(0, -4.5, 2.2):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 2, transform):of_type(t.ASSET_STATION_SIGN, 'eisfeuer_modutram_station_sign')
                :move(0, 4.5, 2.2):add_to_slots()

        end,
        getModelsFn = function()
            return {{
                id = 'station/tram/modutram_platform_double_noaccess_era_b.mdl',
                transf = {
                    0, -1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    -9, 0, 0, 1,
                }
            }, {
                id = 'station/tram/modutram_platform_double_rep_era_c.mdl',
                transf = {
                    0, 1, 0, 0,
                    1, 0, 0, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1,
                }
            }, {
                id = 'station/tram/modutram_platform_double_noaccess_era_b.mdl',
                transf = {
                    0, 1, 0, 0,
                    1, 0, 0, 0,
                    0, 0, 1, 0,
                    9, 0, 0, 1,
                }
            }}
        end
    }
end