function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "track", },
        },
        description = {
            name = _("Track single up"),
            description = _("Platform for waiting passengers."),
            icon = "ui/construction/station/street/platform_passenger_era_a.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "eisfeuer_modutram_track_up_doors_right",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            result.station.builder:add_segment_models_for_tram_track(slotId, {{
                id = 'modutram_track_single_rep_era_c.mdl',
                transf = {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1,
                }
            }})
        end,
        getModelsFn = function()
            return {{
                id = 'modutram_track_single_rep_era_c.mdl',
                transf = {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1,
                }
            }}
        end
    }
end