function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "track", },
        },
        description = {
            name = _("Track single up"),
            description = _("Platform for waiting passengers."),
            icon = "ui/construction/station/street/platform_passenger_era_a.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "eisfeuer_modutram_track_double_doors_right",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            result.station.slots:make_asset_slot(slotId, 1, transform):catenary():move(0, 0, 1):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 1, transform):tram_tracks():move(0.2, 0, 1):add_to_slots()

            result.station.builder:add_vehicle_and_platform_lanes_for('tram_not_electric', slotId, 1)
            result.station.builder:add_vehicle_and_platform_lanes_for('tram_not_electric', slotId, -1)

        end,
        getModelsFn = function()
            return {}
        end
    }
end