local Position = require('modutram_position')
local Matrix = require('modutram_matrix')

function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "track", },
        },
        description = {
            name = _("Track single up"),
            description = _("Platform for waiting passengers."),
            icon = "ui/construction/station/street/platform_passenger_era_a.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "eisfeuer_modutram_track_double_doors_right",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            result.station.slots:make_asset_slot(slotId, 1, transform):catenary():move(0, 0, 1):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 1, transform):tram_tracks():move(0.21, 0, 1):add_to_slots()
            result.station.slots:make_asset_slot(slotId, 1, transform):bus_lane():move(-0.21, 0, 1):add_to_slots()

            result.station.builder:add_vehicle_and_platform_lanes_for('tram_not_electric', slotId, 1)
            result.station.builder:add_vehicle_and_platform_lanes_for('tram_not_electric', slotId, -1)

            local arrow_up_position = Position:new{x = 1.5, y = 0, z = 0}:add_to_matrix(transform)
            local arrow_down_position = Position:new{x = -1.5, y = 0, z = 0}:add_to_matrix(Matrix.rotate_around_z_axis(180, transform))

            result.station.builder:add_model({
                id = 'icons/modutram_arrow.mdl',
                transf = arrow_up_position
            })
            result.station.builder:add_model({
                id = 'icons/modutram_arrow.mdl',
                transf = arrow_down_position
            })
        end,
        getModelsFn = function()
            return {}
        end
    }
end