local transf = require("transf")
local bench = require("modular_tram_station.modules.bench")

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_benches_name"),
            description = _("era_b"),
            icon = "ui/construction/modules/modular_tram_station/benches_era_b.tga"
        }, 
        availability = {
            yearFrom = 1920,
            yearTo = 0
        },
        type = "modutram_asset",
        order = {
            value = 999990912,
        },
        metadata = {
            modutram = {
                themes = { "era_b" },
                themeType = "benches"
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            bench.buildDouble(
                result.modutram:getModule(slotId),
                addModelFn,
                "asset/bench_new.mdl",
                transf.rotZ(-math.pi / 2)
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = "asset/bench_new.mdl",
                    transf = transf.rotZTransl(math.pi / 2, {x = 0, y = -1.5, z = 0})
                }, {
                    id = "asset/bench_new.mdl",
                    transf = transf.rotZTransl(math.pi / 2, {x = 0, y = 1.5, z = 0})
                }
            }
        end
    }
end