function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_sign_name"),
            description = _("bus") .. " " .._("era_b"),
            icon = "ui/achievements/ach_build_bus_stop.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "bus_station_sign",
        order = {
            value = 999990811,
        },
        metadata = {
            modutram = {
                themes = { "era_b" },
                themeType = "bus_station_sign"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'station/road/streetstation/asset/bus_stop_sign_era_b_1.mdl',
                {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -2, 1,
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/road/streetstation/asset/bus_stop_sign_era_b_1.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -2, 1,
                    }
                }
            }
        end
    }
end