local SHELTER_SEGMENT_WIDTH = 1.3

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "shelters", },
        },
        description = {
            name = _("module_shelter_name"),
            description = _("mid") .. " " .. _("era_b"),
            icon = "ui/construction/modules/modular_tram_station/shelter_medium_era_b.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset_shelter",
        order = {
            value = 999990712,
        },
        metadata = {
            modutram = {
                shelterSize = 3.9 * 2,
                themes = { "era_b" },
                themeType = "shelter_medium"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_r_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, SHELTER_SEGMENT_WIDTH * 2, -2, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, SHELTER_SEGMENT_WIDTH, -2, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, 0, -2, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH, -2, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 2, -2, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_l_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 2, -2, 1
                }
            )
            addModelFn(
                "station/road/streetstation/asset/bench_era_b_l_1.mdl",
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.1, -1.95, -2, 1
                }
            )
            addModelFn(
                "station/road/streetstation/asset/bench_era_b_r_1.mdl",
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.1, -1.95, -2, 1
                }
            )
            addModelFn(
                'asset/modutram_schedule_era_b.mdl',
                {
                    -2, 0, 0, 0,
                    0, -2, 0, 0,
                    0, 0, 2, 0,
                    0.45, 1.95, -0.5, 1
                }
            )
            addModelFn(
                "station/road/streetstation/asset/tickets_era_b_1.mdl",
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.0, 3.3, -2, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/road/streetstation/asset/shelter_era_b_r_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, SHELTER_SEGMENT_WIDTH * 2, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, SHELTER_SEGMENT_WIDTH, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, 0, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 2, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_b_l_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 2, -1, 1
                    }
                }, {
                    id = "station/road/streetstation/asset/bench_era_b_l_1.mdl",
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.1, -1.95, -1, 1
                    }
                }, {
                    id = "station/road/streetstation/asset/bench_era_b_r_1.mdl",
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.1, -1.95, -1, 1
                    }
                }, {
                    id = 'asset/modutram_schedule_era_b.mdl',
                    transf = {
                        -2, 0, 0, 0,
                        0, -2, 0, 0,
                        0, 0, 2, 0,
                        0.45, 1.95, 0.5, 1
                    }
                }, {
                    id = "station/road/streetstation/asset/tickets_era_b_1.mdl",
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.0, 3.3, -1, 1
                    }
                }
            }
        end
    }
end