return {
    PLATFORM_SEGMENT_LENGTH = 18,
    DISTANCE_BETWEEN_TWO_TRACKS = 3,
    DISTANCE_BETWEEN_TRACK_AND_PLATFORM = 1.325,
    PLATFORM_DOUBLE_WIDTH = 5.4,
    PLATFORM_SINGLE_WIDTH = 3.3
}