local modulesutil = require "modulesutil"

function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "Tram", },
        },
        description = {
            name = _("module_street_connection_double_name"),
            description = _("era_c"),
            icon = "ui/construction/station/street/platform_entrance.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset_tram_street_connection",
        order = {
            value = 999990105,
        },
        metadata = {
            modutram = {
                themes = { "era_c" },
                themeType = "tram_street_connection"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            result.modutram:addStreet("modutram_town_xs_new_era_c.lua", "ELECTRIC", {
                { modulesutil.mul(transform, {0, 0, 0, 1}), modulesutil.mul(transform, {0, 10, 0, 0})},
                { modulesutil.mul(transform, {0, 10, 0, 1}), modulesutil.mul(transform, {0, 10, 0, 0})}
            }, {1})
        end,
        getModelsFn = function()
            return {}
        end
    }
end