local makeGroundFaceFromGridModule = require("modutram.utils.makeGroundFaceFromGridModule")
local makeLot = require("modutram.utils.makeLot")
local trammoduleutils = require("utils.trammoduleutils")
local transf = require("transf")

function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "Tram", },
        },
        description = {
            name = _("tram_tracks"),
            description = _("Up 1000mm"),
            icon = "ui/achievements/ach_first_electric_train_arrived.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_tram_up_266cm",
        order = {
            value = 999990103,
        },
        metadata = {
            modutram = {
                themes = { "era_c" },
                themeType = "tram_up"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local module = result.modutram:getModule(slotId)

            module:addAssetSlot(result, 1, "modutram_asset_catenary", transf.mul(transform, transf.transl({x = 0, y = 0, z = 1})))

            local groundFace = makeGroundFaceFromGridModule(module, transform)
            makeLot(result, groundFace)

            addModelFn("station/tram/modular_tram_station/tram_track_rep_era_c.mdl")          
            
            trammoduleutils.addCrossing(module, addModelFn)

            local terminalPosition = 0
            module:handleTerminals(function (terminalGroup)
                local vehicleNodeOffset = terminalGroup.vehicleStopAlignment == 'top' and 2 or 0

                if module:hasTerminals() then
                    terminalGroup:attachVehicleTerminal(terminalPosition, vehicleNodeOffset)
                else
                    terminalPosition = terminalGroup:addVehicleTerminalModel(
                        "station/tram/modular_tram_station/path/tram_stop.mdl",
                        transform,
                        1 + vehicleNodeOffset
                    )
                end
            end)

            module:handleLanes(function ()
                if not module:hasTerminals() then
                    addModelFn("station/tram/modular_tram_station/path/tram_lane.mdl")
                end
            end)
        end,
        getModelsFn = function()
            return {{
                id = "station/tram/modular_tram_station/tram_track_rep_era_c.mdl",
                transf = {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, 0, 1,
                }
            }}
        end
    }
end