local makeGroundFaceFromGridModule = require("modutram.utils.makeGroundFaceFromGridModule")
local makeLot = require("modutram.utils.makeLot")
local transf = require("transf")

function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "Tram", },
        },
        description = {
            name = _("tram_tracks"),
            description = _("1000mm"),
            icon = "ui/achievements/ach_first_electric_train_arrived.tga"
        }, 
        availability = {
            yearFrom = 1850,
            yearTo = 0
        },
        type = "modutram_tram_bidirectional_left_600cm",
        order = {
            value = 999990102,
        },
        metadata = {
            modutram = {
                themes = { "era_c" },
                themeType = "tram_bidirectional_left",
                widthInCm = 600
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local module = result.modutram:getModule(slotId)

            local groundFace = makeGroundFaceFromGridModule(module, transform)
            makeLot(result, groundFace)

            addModelFn("station/tram/modular_tram_station/tram_track_rep_era_c.mdl", transf.transl({x = -1.5, y = 0, z = 0}))
            addModelFn("station/tram/modular_tram_station/tram_track_rep_era_c.mdl", transf.transl({x = 1.5, y = 0, z = 0}))
        end,
        getModelsFn = function()
            return {{
                id = "station/tram/modular_tram_station/tram_track_rep_era_c.mdl",
                transf = {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    -1.5, 0, 0, 1,
                }
            }, {
                id = "station/tram/modular_tram_station/tram_track_rep_era_c.mdl",
                transf = {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    1.5, 0, 0, 1,
                }
            }}
        end
    }
end