local transf = require("transf")
local bench = require("modules.bench")

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_bench_name"),
            description = _("era_a"),
            icon = "ui/construction/modules/modular_tram_station/bench_era_a.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset",
        order = {
            value = 999990901,
        },
        metadata = {
            modutram = {
                themes = { "era_a" },
                themeType = "bench",
                themeExcludes = { "destination_display" },
                themeTranslations = {
                    era_a = _("era_a")
                }
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            bench.buildSingle(
                result.modutram:getModule(slotId),
                addModelFn,
                "asset/bench_old.mdl",
                transf.rotZ(-math.pi / 2)
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = "asset/bench_old.mdl",
                    transf = transf.rotZ(math.pi / 2)
                }
            }
        end
    }
end