function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_billboard_name"),
            description = _("era_a") .. " " .. _("poster_1"),
            icon = "ui/achievements/ach_build_bus_stop.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset",
        order = {
            value = 999991101,
        },
        metadata = {
            modutram = {
                themes = { "era_a" },
                themeType = "billboard_small"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local asset = result.modutram:getModule(slotId)
            local seed = params.seed + asset:getSlotId()
            local billboardId = (seed  % 2) + 1

            addModelFn(
                'station/road/streetstation/asset/com_small_era_a_' .. billboardId .. '.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -1, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/road/streetstation/asset/com_small_era_a_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end