local lighting = require("modular_tram_station.modules.lighting")

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_lamp_name"),
            description = _("era_a"),
            icon = "ui/construction/modules/modular_tram_station/lighting_era_a.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset_lighting",
        order = {
            value = 999991001,
        },
        metadata = {
            modutram = {
                themes = { "era_a" },
                themeType = "lighting"
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            lighting.build(
                result.modutram:getModule(slotId):getParentGridModule(),
                result.modutram.config.gridModuleLength,
                addModelFn,
                "street/street_light_eu_a.mdl"
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = "street/street_light_eu_a.mdl",
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end