function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_station_sign_name"),
            description = _("era_a"),
            icon = "ui/construction/modules/modular_tram_station/station_name_sign_era_a.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset_station_name_sign",
        order = {
            value = 999990802,
        },
        metadata = {
            modutram = {
                themes = { "era_a" },
                themeType = "station_name_sign"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'station/rail/asset/era_a_station_name.mdl',
                {
                    0, -1, 0, 0,
                    1, 0, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -3.05, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/rail/asset/era_a_station_name.mdl',
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -3.05, 1,
                    }
                }
            }
        end
    }
end