local transf = require("transf")
local bench = require("modular_tram_station.modules.bench")

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_benches_name"),
            description = _("wooden"),
            icon = "ui/construction/modules/modular_tram_station/benches_wood.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset",
        order = {
            value = 999990905,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            bench.buildDouble(
                result.modutram:getModule(slotId),
                addModelFn,
                "asset/commercial/era_a/com_1_ground_double_bench_a.mdl",
                transf.rotZ(math.pi / 2)
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/commercial/era_a/com_1_ground_double_bench_a.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        -1.5, 0, -1, 1,
                    }
                }, {
                    id = 'asset/commercial/era_a/com_1_ground_double_bench_a.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.5, 0, -1, 1,
                    }
                }
            }
        end
    }
end