function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "billboards", },
        },
        description = {
            name = _("module_billboard_large_name"),
            description = _("era_a") .. " " .. _("poster_2"),
            icon = "ui/achievements/ach_build_bus_stop.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "g_decoration",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'station/road/streetstation/asset/com_large_era_c_2.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -1, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/road/streetstation/asset/com_large_era_c_2.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end