local t = require('modutram_types')
local Position = require('modutram_position')

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "tracks", },
        },
        description = {
            name = _("module_catenary_name"),
            description = _("era_a"),
            icon = "ui/tracks/electrify.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "eisfeuer_modutram_catenary",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local track_type = result.station:module(slotId):get_track().type

            local catenary_wire_position = (track_type == t.TRACK_DOUBLE_DOORS_RIGHT) and 1.5 or 0
            local catenary_pole_position = (track_type == t.TRACK_DOUBLE_DOORS_RIGHT) and 0 or ((track_type == t.TRACK_UP_DOORS_RIGHT) and -1.5 or 1.5)

            local catenary_components = {
                {
                    id = 'asset/modutram_catenary_pole_era_a.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        catenary_pole_position, 0, 0, 1
                    }
                }, {
                    id = 'station/tram/modutram_catenary_wire.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        catenary_wire_position, 0, 0, 1
                    }
                }
            }

            if track_type ~= t.TRACK_UP_DOORS_RIGHT then
                table.insert(catenary_components, {
                    id = 'asset/modutram_catenary_suspension_era_a.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        catenary_pole_position, 0, -0.2, 1
                    }
                })
            end

            if track_type ~= t.TRACK_DOWN_DOORS_RIGHT then
                table.insert(catenary_components, {
                    id = 'asset/modutram_catenary_suspension_era_a.mdl',
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        catenary_pole_position, 0, -0.2, 1
                    }
                })
            end

            if track_type == t.TRACK_DOUBLE_DOORS_RIGHT then
                table.insert(catenary_components, {
                    id = 'station/tram/modutram_catenary_wire.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        -catenary_wire_position, 0, 0, 1
                    }
                })
            end

            result.station.builder:add_segment_models_for_tram_track(slotId, catenary_components)

            if result.station:planning_mode_is_active() then
                result.station.builder:add_model({
                    id = 'icons/modutram_lightning.mdl',
                    transf = Position:new{x = 0, y = 0, z = -0.95}:add_to_matrix(transform)
                })
            end
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/modutram_catenary_pole_era_a.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }, {
                    id = 'asset/modutram_catenary_suspension_era_a.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1
                    }
                }, {
                    id = 'asset/modutram_catenary_suspension_era_a.mdl',
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1
                    }
                }
            }
        end
    }
end