function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "tracks", },
        },
        description = {
            name = _("Catenary"),
            description = _("Era A"),
            icon = "ui/construction/asset/default_multi_bench_new.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "eisfeuer_modutram_catenary",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'asset/modutram_catenary_pole_era_a.mdl',
                {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 1, -1, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/modutram_catenary_pole_era_a.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end