function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "fences", },
        },
        description = {
            name = _("module_fence_name"),
            description = "6m " .. _("era_a"),
            icon = "ui/achievements/ach_track_length.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "g_fence_6m",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'asset/modutram_fence_6m_era_a.mdl',
                {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -1, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/modutram_fence_6m_era_a.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end