function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "lamps", },
        },
        description = {
            name = _("Lamp"),
            description = _("Makes Light."),
            icon = "ui/construction/asset/default_multi_lamp.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "g_decoration",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'asset/lamp_old.mdl',
                {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -1, 1
                }
            )
        end,
        getModelsFn = function()
            return {{
                id = 'asset/lamp_old.mdl',
                transf = {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -1, 1,
                }
            }}
        end
    }
end