local SHELTER_SEGMENT_WIDTH = 1.3

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "shelters", },
        },
        description = {
            name = _("module_shelter_name"),
            description = _("large") .. " " .. _("era_a"),
            icon = "ui/models/station/bus/small_old.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "g_shelter",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_r_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, SHELTER_SEGMENT_WIDTH * 3.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, SHELTER_SEGMENT_WIDTH * 2.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, SHELTER_SEGMENT_WIDTH * 1.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 1.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 2.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 3.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_a_l_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 3.5, -1, 1
                }
            )
            addModelFn(
                'asset/bench_old.mdl',
                {
                    0, -1, 0, 0,
                    1, 0, 0, 0,
                    0, 0, 1, 0,
                    0.5, -3.9, -1, 1
                }
            )
            addModelFn(
                'asset/bench_old.mdl',
                {
                    0, -1, 0, 0,
                    1, 0, 0, 0,
                    0, 0, 1, 0,
                    0.5, 0, -1, 1
                }
            )
            addModelFn(
                'asset/modutram_schedule_era_a.mdl',
                {
                    -2, 0, 0, 0,
                    0, -2, 0, 0,
                    0, 0, 2, 0,
                    0.25, 2.6, 0.5, 1
                }
            )
            addModelFn(
                'asset/bench_old.mdl',
                {
                    0, -1, 0, 0,
                    1, 0, 0, 0,
                    0, 0, 1, 0,
                    0.5, 3.9, -1, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/road/streetstation/asset/shelter_era_a_r_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, SHELTER_SEGMENT_WIDTH * 3.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, SHELTER_SEGMENT_WIDTH * 2.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, SHELTER_SEGMENT_WIDTH * 1.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 1.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 2.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 3.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_a_l_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 3.5, -1, 1
                    }
                }, {
                    id = 'asset/bench_old.mdl',
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0.5, -3.9, -1, 1
                    }
                }, {
                    id = 'asset/bench_old.mdl',
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0.5, 0, -1, 1
                    }
                }, {
                    id = 'asset/modutram_schedule_era_a.mdl',
                    transf = {
                        -2, 0, 0, 0,
                        0, -2, 0, 0,
                        0, 0, 2, 0,
                        0.25, 2.6, 0.5, 1
                    }
                }, {
                    id = 'asset/bench_old.mdl',
                    transf = {
                        0, -1, 0, 0,
                        1, 0, 0, 0,
                        0, 0, 1, 0,
                        0.5, 3.9, -1, 1
                    }
                }
            }
        end
    }
end