local SHELTER_SEGMENT_WIDTH = 1.3

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "shelters", },
        },
        description = {
            name = _("module_shelter_name"),
            description = _("small") .. " " .. _("era_b"),
            icon = "ui/models/station/bus/small_mid.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "g_shelter",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_r_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                }
            )
            addModelFn(
                'station/road/streetstation/asset/shelter_era_b_l_1.mdl',
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.8, -SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                }
            )
            addModelFn(
                "station/road/streetstation/asset/bench_era_b_l_1.mdl",
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.1, 0, -1, 1
                }
            )
            addModelFn(
                "station/road/streetstation/asset/bench_era_b_r_1.mdl",
                {
                    0, 1, 0, 0,
                    -1, 0, 0, 0,
                    0, 0, 1, 0,
                    1.1, 0, -1, 1
                }
            )
            addModelFn(
                'asset/modutram_schedule_era_b.mdl',
                {
                    0, 2, 0, 0,
                    -2, 0, 0, 0,
                    0, 0, 2, 0,
                    1.2, 1.95, 0.5, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/road/streetstation/asset/shelter_era_b_r_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_b_rep_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                    }
                }, {
                    id = 'station/road/streetstation/asset/shelter_era_b_l_1.mdl',
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.8, -SHELTER_SEGMENT_WIDTH * 0.5, -1, 1
                    }
                }, {
                    id = "station/road/streetstation/asset/bench_era_b_l_1.mdl",
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.1, 0, -1, 1
                    }
                }, {
                    id = "station/road/streetstation/asset/bench_era_b_r_1.mdl",
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        1.1, 0, -1, 1
                    }
                }, {
                    id = 'asset/modutram_schedule_era_b.mdl',
                    transf = {
                        0, 2, 0, 0,
                        -2, 0, 0, 0,
                        0, 0, 2, 0,
                        1.2, 1.95, 0.5, 1
                    }
                }
            }
        end
    }
end