function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "signs", },
        },
        description = {
            name = _("Bus Stop Sign"),
            description = _("Art Nouveau"),
            icon = "ui/construction/asset/default_multi_bench_old.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "g_decoration",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'station/road/streetstation/asset/bus_stop_sign_era_a_1.mdl',
                {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -1, 1,
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'station/road/streetstation/asset/bus_stop_sign_era_a_1.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end