function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "signs", },
        },
        description = {
            name = _("module_station_sign_name"),
            description = _("era_c"),
            icon = "ui/hud/depot_road.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "eisfeuer_modutram_station_sign",
        order = {
            value = 7,
        },
        metadata = {
            passenger = true,
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'asset/modutram_station_name_sign_era_c.mdl',
                {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 0, -2.05, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/modutram_station_name_sign_era_c.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -2.05, 1,
                    }
                }
            }
        end
    }
end