local modulesutil = require "modulesutil"

local function getStreetTramProperty(gridModule)
    if not gridModule:getOption("hasTramRails") then
        return "NO"
    end

    return gridModule:hasAsset(1) and "ELECTRIC" or "YES"
end

function data()
    return {
        cost = {
            price = 20000,
        },
        category = {
            categories = { "Tram", },
        },
        description = {
            name = _("module_street_connection_double_name"),
            description = _("era_a"),
            icon = "ui/construction/station/street/platform_entrance.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset_tram_street_connection",
        order = {
            value = 999990105,
        },
        metadata = {
            modutram = {
                themes = { "era_a" },
                themeType = "tram_street_connection"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local asset = result.modutram:getModule(slotId)
            local gridModule = asset:getParentGridModule()

            if gridModule:isBidirectionalRightTrack() then
                result.modutram:addStreet("modutram_town_xs_new_era_a.lua", getStreetTramProperty(gridModule), {
                    { modulesutil.mul(transform, {0, 0, 0, 1}), modulesutil.mul(transform, {0, 10, 0, 0})},
                    { modulesutil.mul(transform, {0, 10, 0, 1}), modulesutil.mul(transform, {0, 10, 0, 0})}
                }, {1})

                return
            end

            if (gridModule:isUpGoingTrack() and asset:getId() == 3) or (gridModule:isDownGoingTrack() and asset:getId() == 4) then
                result.modutram:addStreet("modutram_town_xs_one_way_new_era_a.lua", getStreetTramProperty(gridModule), {
                    { modulesutil.mul(transform, {0, 0, 0, 1}), modulesutil.mul(transform, {0, 10, 0, 0})},
                    { modulesutil.mul(transform, {0, 10, 0, 1}), modulesutil.mul(transform, {0, 10, 0, 0})}
                }, {1})

                return
            end

            if (gridModule:isUpGoingTrack() and asset:getId() == 4) or (gridModule:isDownGoingTrack() and asset:getId() == 3) then
                result.modutram:addStreet("modutram_town_xs_one_way_new_era_a.lua", getStreetTramProperty(gridModule), {
                    { modulesutil.mul(transform, {0, 10, 0, 1}), modulesutil.mul(transform, {0, -10, 0, 0})},
                    { modulesutil.mul(transform, {0, 0, 0, 1}), modulesutil.mul(transform, {0, -10, 0, 0})}
                }, {0})

                return
            end
        end,
        getModelsFn = function()
            return {}
        end
    }
end