function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_bench_name"),
            description = _("era_c"),
            icon = "ui/construction/modules/modular_tram_station/bench_era_c.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset",
        order = {
            value = 999990921,
        },
        metadata = {
            modutram = {
                themes = { "era_c" },
                themeType = "bench"
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            addModelFn(
                'asset/modutram_bench_era_c.mdl',
                {
                    1, 0, 0, 0,
                    0, 1, 0, 0,
                    0, 0, 1, 0,
                    0, 1, -1, 1
                }
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/modutram_bench_era_c.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end