local transf = require("transf")
local destinationDisplay = require("modular_tram_station.modules.destination_display")

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_destination_display_name"),
            description = _("era_c"),
            icon = "ui/construction/modules/modular_tram_station/destination_display_era_c.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "modutram_asset_sign",
        order = {
            value = 999990823,
        },
        metadata = {
            modutram = {
                themes = { "era_c" },
                themeType = "destination_display",
            },
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            destinationDisplay.build(result.modutram:getModule(slotId), addModelFn, "asset/modutram_destination_display_era_c.mdl", true)
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/modutram_destination_display_era_c.mdl',
                    transf = transf.transl({x = 0, y = 0, z = 0})
                }
            }
        end
    }
end