local fence = require("modular_tram_station.modules.fence")

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_fence_name"),
            description = _("era_c"),
            icon = "ui/construction/modules/modular_tram_station/fence_era_c.tga"
        }, 
        availability = {
            yearFrom = 1980,
            yearTo = 0
        },
        type = "modutram_asset_fence",
        order = {
            value = 999991221,
        },
        metadata = {
            modutram = {
                themes = { "era_c" },
                themeType = "fence"
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            local module = result.modutram:getModule(slotId)
            fence.build(result.modutram, module, addModelFn, 1.2, "asset/modutram_fence_120cm_era_c.mdl", "asset/modutram_splash_guard_120cm_era_c.mdl")
        end,
        getModelsFn = function()
            return {
                {
                    id = 'asset/modutram_fence_120cm_era_c.mdl',
                    transf = {
                        1, 0, 0, 0,
                        0, 1, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end