local lighting = require("modules.lighting")

function data()
    return {
        cost = {
            price = 1000,
        },
        category = {
            categories = { "Decoration", },
        },
        description = {
            name = _("module_lamp_name"),
            description = _("era_c"),
            icon = "ui/construction/asset/default_multi_lamp.tga"
        }, 
        availability = {
            yearFrom = 0,
            yearTo = 0
        },
        type = "modutram_asset_lighting",
        order = {
            value = 999991021,
        },
        metadata = {
            modutram = {
                themes = { "era_c" },
                themeType = "lighting"
            }
        },
        updateFn = function(result, transform, tag, slotId, addModelFn, params)
            lighting.build(
                result.modutram:getModule(slotId):getParentGridModule(),
                result.modutram.config.gridModuleLength,
                addModelFn,
                "asset/modutram_lamp_era_c.mdl",
                "asset/modutram_lamp_era_c_double.mdl"
            )
        end,
        getModelsFn = function()
            return {
                {
                    id = "asset/modutram_lamp_era_c.mdl",
                    transf = {
                        0, 1, 0, 0,
                        -1, 0, 0, 0,
                        0, 0, 1, 0,
                        0, 0, -1, 1,
                    }
                }
            }
        end
    }
end