function data()
    return {
      en = {
        ["modular_tram_station_name"] = "Tram Station",
        ["modular_tram_station_desc"] = "Modular station for trams and bus rapid transit.",
        -- Blueprint settings keys
        ["modutram_planning_mode"] = "Planning mode",
        ["modutram_platform_placing_pattern"] = "Platform layout",
        ["modutram_tram_tracks"] = "Tram tracks",
        ["modutram_electrification"] = "Electrification",
        ["modutram_bus"] = "Bus",
        ["modutram_street_connections"] = "Street connections",
        ["modutram_platforms_left"] = "Platforms left",
        ["modutram_platforms_right"] = "Platforms right",
        ["modutram_platform_length"] = "Platform length",
        ["modutram_platform_passenger_access"] = "Platform access",
        ["modutram_shelter"] = "Shelter",
        ["modutram_shelter_size"] = "Shelter size",
        ["modutram_fences"] = "Fences",
        ["modutram_lamps"] = "Lamps",
        ["modutram_benches"] = "Benches",
        ["modutram_billboards"] = "Billboards",
        ["modutram_stop_signs"] = "Stop signs",
        ["modutram_station_signs"] = "Station signs",
        ["modutram_destination_display"] = "Destination displays",
        -- Blueprint settings options
        ["era_a"] = "Era A",
        ["era_b"] = "Era B",
        ["era_c"] = "Era C",
        ["left"] = "Left",
        ["right"] = "Right",
        ["both"] = "Both",
        ["small"] = "Small",
        ["mid"] = "Medium",
        ["large"] = "Large",
        -- Modules
        ["module_bus_lane_name"] = "Bus lane",
        ["module_bus_lane_desc"] = "Allows busses to pass and stop on this track.",
        ["module_platform_access_name"] = "Platform access",
        ["module_platform_single_left_name"] = "Single platform (tram at the left)",
        ["module_platform_single_right_name"] = "Single platform (tram at the right)",
        ["module_platform_double_name"] = "Double platform",
        ["module_street_connection_double_name"] = "Two way street connection",
        ["module_street_connection_out_name"] = "One way street connection (exit)",
        ["module_street_connection_in_name"] = "One way street connection (entrance)",
        ["module_track_double_name"] = "Two way tracks",
        ["module_track_down_name"] = "One way track (right direction)",
        ["module_track_up_name"] = "One way track (left direction)",
        ["module_track_desc"] = "Empty track - After placing you have to place tram tracks or bus lanes",
        -- Asset Modules
        ["module_bench_name"] = "Bench",
        ["module_lamp_name"] = "Lamp",
        ["for_double_platform"] = "Use for double platforms",
        ["wooden"] = "Wooden",
        ["module_billboard_name"] = "Billboard",
        ["module_billboard_large_name"] = "Billboard large",
        ["module_billboard_clp_name"] = "City light poster",
        ["poster_1"] = "Poster 1",
        ["poster_2"] = "Poster 2",
        ["poster_3"] = "Poster 3",
        ["module_catenary_name"] = "Catenary",
        ["module_shelter_name"] = "Shelter",
        ["module_destination_display_name"] = "Destination display",
        ["module_fence_name"] = "Fence",
        ["module_splash_guard_name"] = "Splash guard",
        ["module_sign_name"] = "Sign",
        ["tram_tracks"] = "Tram tracks",
        ["module_station_sign_name"] = "Station name sign",
        ["Bus"] = "Bus"
      },
      de = {
        ["Modular Tram Station (Beta)"] = "Modulere Straßenbahnhaltestelle (Beta)",
        ["modular_tram_station_name"] = "Straßenbahnhaltestelle",
        ["modular_tram_station_desc"] = "Modulare Haltestelle für Straßenbahnen und Bus-Rapid-Transit-Systeme.",
        -- Blueprint settings keys
        ["modutram_planning_mode"] = "Planungsmodus",
        ["modutram_platform_placing_pattern"] = "Bahnsteiganordnung",
        ["modutram_tram_tracks"] = "Straßenbahngleise",
        ["modutram_electrification"] = "Elektrifizierung",
        ["modutram_bus"] = "Bus",
        ["modutram_street_connections"] = "Straßenanschlüsse",
        ["modutram_platforms_left"] = "Bahnsteige links",
        ["modutram_platforms_right"] = "Bahnsteige rechts",
        ["modutram_platform_length"] = "Bahnsteiglänge",
        ["modutram_platform_passenger_access"] = "Bahnsteigzugang",
        ["modutram_shelter"] = "Unterstand",
        ["modutram_shelter_size"] = "Größe des Unterstands",
        ["modutram_fences"] = "Zäune",
        ["modutram_lamps"] = "Lampen",
        ["modutram_benches"] = "Bänke",
        ["modutram_billboards"] = "Werbung",
        ["modutram_stop_signs"] = "Haltestellenschilder",
        ["modutram_station_signs"] = "Schilder mit Stationsnamen",
        ["modutram_destination_display"] = "Zielanzeiger",
        -- Blueprint settings options
        ["era_a"] = "Epoche A",
        ["era_b"] = "Epoche B",
        ["era_c"] = "Epoche C",
        ["left"] = "Links",
        ["right"] = "Rechts",
        ["both"] = "Beide Seiten",
        ["small"] = "Klein",
        ["mid"] = "Mittelgroß",
        ["large"] = "Groß",
        -- Modules
        ["module_bus_lane_name"] = "Busspur",
        ["module_bus_lane_desc"] = "Busse dürfen auf dieser Spur fahren und halten.",
        ["module_platform_access_name"] = "Bahnsteigzugang",
        ["module_platform_single_left_name"] = "Einzelbahnsteig (Straßenbahn Links)",
        ["module_platform_single_right_name"] = "Einzelbahnsteig (Straßenbahn Rechts)",
        ["module_platform_double_name"] = "Doppelbahnsteig",
        ["module_street_connection_double_name"] = "Straßenanschluss (keine Einbahnstraße)",
        ["module_street_connection_out_name"] = "Straßenanschluss (Einbahnstraße - Ausfahrt)",
        ["module_street_connection_in_name"] = "Straßenanschluss (Einbahnstraße - Einfahrt)",
        ["module_track_double_name"] = "Doppelgleis",
        ["module_track_down_name"] = "Einzelgleis (Fahrtrichtung rechts)",
        ["module_track_up_name"] = "Einzelgleis (Fahrtrichtung links)",
        ["module_track_desc"] = "Nach Platzierung muss noch ein Straßenbahngleis oder eine Busspur platziert werden.",
        -- Asset Modules
        ["module_bench_name"] = "Bank",
        ["module_lamp_name"] = "Lampe",
        ["for_double_platform"] = "Für Doppelbahnsteig",
        ["wooden"] = "Holzbank",
        ["module_billboard_name"] = "Werbung",
        ["module_billboard_large_name"] = "Große Werbung",
        ["module_billboard_clp_name"] = "City light poster",
        ["poster_1"] = "Plakat 1",
        ["poster_2"] = "Plakat 2",
        ["poster_3"] = "Plakat 3",
        ["module_catenary_name"] = "Oberleitung",
        ["module_shelter_name"] = "Unterstand",
        ["module_destination_display_name"] = "Zielanzeiger",
        ["module_fence_name"] = "Zaun",
        ["module_splash_guard_name"] = "Spritschutzzaun",
        ["module_sign_name"] = "Haltestellenschild",
        ["tram_tracks"] = "Straßenbahngleis",
        ["module_station_sign_name"] = "Schild mit Stationsnamen",
        ["Bus"] = "Bus",
        -- Categories
        ["benches"] = "Bänke",
        ["billboards"] = "Werbung",
        ["fences"] = "Zäune",
        ["lamps"] = "Beleuchtung",
        ["shelters"] = "Unterstände",
        ["signs"] = "Schilder",
        ["platforms"] = "Bahnsteige"
      },
    }
end
    