function data()
    return {
      en = {
        ["modular_tram_station_name"] = "Modular Tram Station",
        ["modular_tram_station_desc"] = "Modular station for trams and bus rapid transit.",
        -- Templates
        ["template_line_operation"] = "Alternating direction",
        ["template_directional_operation"] = "Sorted direction",
        ["template_oneway_operation"] = "Same direction",
        ["template_from_scratch"] = "From scratch",
        -- Blueprint settings keys
        ["modutram_base_tracks"] = "Amount of tracks",
        ["modutram_base_platform_length"] = "Platform length",
        ["modutram_base_center_module"] = "Center Module",
        ["modutram_base_vehicle"] = "Vehicle",
        ["modutram_base_shelter"] = "Shelter",
        ["modutram_base_street_connections"] = "Street connection",        
        ["modutram_theme"] = "Theme",
        -- Blueprint settings options
        ["era_a"] = "Era A",
        ["era_b"] = "Era B",
        ["era_c"] = "Era C",
        ["left"] = "Left",
        ["right"] = "Right",
        ["both"] = "Both",
        ["small"] = "Small",
        ["mid"] = "Medium",
        ["large"] = "Large",
        ["modutram_option_tracks"] = "Tracks",
        ["modutram_option_platform"] = "Island Platform",
        ["bus"] = "Bus",
        ["tram"] = "Horse or Steam tram",
        ["etram"] = "Electric Tram",
        -- Track Modules
        ["module_tram_track_name"] = "Tram tracks",
        ["module_tram_track_desc"] = "Trafficable for tram and bus",
        ["module_bus_lane_name"] = "Bus lane",
        ["module_bus_lane_desc"] = "Without tram tracks.",
        ["track_bidirectional_right"] = "Bidirectional tracks",
        ["track_up"] = "One way track (left direction)",
        ["track_down"] = "One way track (right direction)",
        -- Platform Modules
        ["module_platform_single_left_name"] = "Side platform (tram at the left)",
        ["module_platform_single_right_name"] = "Side platform (tram at the right)",
        ["module_platform_double_name"] = "Island platform",
        ["module_street_connection"] = "Street connection",
        ["street_connection_desc"] = "The connection automatically adjusts to the track module used.",
        ["module_platform_access_name"] = "Platform access",
        ["ramp_module_desc"] = "You can chain more of these modules to build a longer foot path.",
        -- Asset Modules
        ["module_bench_name"] = "Bench",
        ["module_benches_name"] = "Two Benches",
        ["module_lamp_name"] = "Lighting",
        ["wooden"] = "Wooden",
        ["module_billboard_name"] = "Billboard",
        ["module_billboard_clp_name"] = "City light poster",
        ["module_catenary_name"] = "Catenary",
        ["module_shelter_name"] = "Shelter",
        ["module_destination_display_name"] = "Destination display",
        ["module_fence_name"] = "Fence",
        ["module_sign_name"] = "Sign",
        ["module_station_sign_name"] = "Station name sign",
        -- Bus Stops
        ["bus_stop"] = "Bus Stop"
      },
      de = {
        ["Modular Tram Station"] = "Modulere Straßenbahnhaltestelle",
        ["modular_tram_station_name"] = "Straßenbahnhaltestelle",
        ["modular_tram_station_desc"] = "Modulare Haltestelle für Straßenbahnen und Bus-Rapid-Transit-Systeme.",
        -- Templates
        ["template_line_operation"] = "Richtung abwechseld",
        ["template_directional_operation"] = "Richtung sortiert",
        ["template_oneway_operation"] = "Richtung gleich",
        ["template_from_scratch"] = "Eigenbau",
        -- Blueprint settings keys
        ["modutram_base_tracks"] = "Anzahl Gleise/Spuren",
        ["modutram_base_platform_length"] = "Bahn-/Bussteiglänge",
        ["modutram_base_center_module"] = "Modul in der Mitte",
        ["modutram_base_vehicle"] = "Fahrzeug",
        ["modutram_base_shelter"] = "Unterstand",
        ["modutram_base_street_connections"] = "Straßenanschluss",        
        ["modutram_theme"] = "Aussehen",
        -- Blueprint settings options
        ["era_a"] = "Epoche A",
        ["era_b"] = "Epoche B",
        ["era_c"] = "Epoche C",
        ["left"] = "Links",
        ["right"] = "Rechts",
        ["both"] = "Beide Seiten",
        ["small"] = "Klein",
        ["mid"] = "Mittelgroß",
        ["large"] = "Groß",
        ["modutram_option_tracks"] = "Mittelgleise",
        ["modutram_option_platform"] = "Mittelbahnsteig",
        ["bus"] = "Bus",
        ["tram"] = "Pferde- / Dampfbahn",
        ["etram"] = "Electr. Straßenbahn",
        -- Track Modules
        ["module_tram_track_name"] = "Straßenbahngleise",
        ["module_tram_track_desc"] = "Befahrbar für Straßenbahn und Bus",
        ["module_bus_lane_name"] = "Busspur",
        ["module_bus_lane_desc"] = "Ohne Straßenbahngleise.",
        ["track_bidirectional_right"] = "Doppelspur",
        ["track_up"] = "Einzelspur (Fahrtrichtung rechts)",
        ["track_down"] = "Einzelspur (Fahrtrichtung links)",
        -- Platform Modules
        ["module_platform_single_left_name"] = "Seitenbahnsteig (Straßenbahn Links)",
        ["module_platform_single_right_name"] = "Seitenbahnsteig (Straßenbahn Rechts)",
        ["module_platform_double_name"] = "Inselbahnsteig",
        ["module_street_connection"] = "Straßenanschluss",
        ["street_connection_desc"] = "Anschluss passt sich an das Straßenmodul an.",
        ["module_platform_access_name"] = "Bahnsteigzugang",
        ["ramp_module_desc"] = "Mehrere dieser Module nebeneinander erweitern den Fußweg zum Zugang.",
        -- Asset Modules
        ["module_bench_name"] = "Bank",
        ["module_benches_name"] = "Zwei Bänke",
        ["module_lamp_name"] = "Beleuchtung",
        ["wooden"] = "Holzbank",
        ["module_billboard_name"] = "Werbung",
        ["module_billboard_clp_name"] = "City light poster",
        ["module_catenary_name"] = "Oberleitung",
        ["module_shelter_name"] = "Unterstand",
        ["module_destination_display_name"] = "Zielanzeiger",
        ["module_fence_name"] = "Zaun",
        ["module_sign_name"] = "Haltestellenschild",
        ["module_station_sign_name"] = "Schild mit Stationsnamen",
        -- Bus Stops
        ["bus_stop"] = "Bushaltestelle"
      },
    }
end
    